//
// Linux_Base.mof
//
// Copyright (c) 2002, International Business Machines
//
// THIS FILE IS PROVIDED UNDER THE TERMS OF THE COMMON PUBLIC LICENSE
// ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS FILE
// CONSTITUTES RECIPIENTS ACCEPTANCE OF THE AGREEMENT.
//
// You can obtain a current copy of the Common Public License from
// http://oss.software.ibm.com/developerworks/opensource/license-cpl.html
//
// Author:       Heidi Neumann <heidineu@de.ibm.com>
// Contributors:
//
// Description:
// CIM classes for Linux Base System Instrumentation
//


#pragma locale ("en_US")

// ===================================================================
// 	Linux_ComputerSystem
// ===================================================================


instance of PG_ProviderModule
{
   Name = "OSBase_ComputerSystemProviderModule";
   //The library name on disk
   Location = "cmpiOSBase_ComputerSystemProvider";
   Vendor = "SBLIM";
   Version = "2.0.0";
   InterfaceType = "CMPI";
   InterfaceVersion = "2.0.0";
};

instance of PG_Provider
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "OSBase_ComputerSystemProviderModule";
   // The provider name as referenced in the code
   Name = "OSBase_ComputerSystem";
};

instance of PG_ProviderCapabilities
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "OSBase_ComputerSystemProviderModule";
   //The provider name as defined in PG_Provider
   ProviderName = "OSBase_ComputerSystem";
   CapabilityID = "1";
   //Name of the CIM class as defined in the mof
   ClassName = "Linux_ComputerSystem";
   Namespaces = {"root/cimv2"};
   ProviderType = { 2 }; // Instance
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};

// ===================================================================
// 	Linux_OperatingSystem
// ===================================================================

instance of PG_ProviderModule
{
   Name = "OSBase_OperatingSystemProviderModule";
   //The library name on disk
   Location = "cmpiOSBase_OperatingSystemProvider";
   Vendor = "SBLIM";
   Version = "2.0.0";
   InterfaceType = "CMPI";
   InterfaceVersion = "2.0.0";
};

instance of PG_Provider
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "OSBase_OperatingSystemProviderModule";
   // The provider name as referenced in the code
   Name = "OSBase_OperatingSystem";
};

instance of PG_ProviderCapabilities
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "OSBase_OperatingSystemProviderModule";
   //The provider name as defined in PG_Provider
   ProviderName = "OSBase_OperatingSystem";
   CapabilityID = "1";
   //Name of the CIM class as defined in the mof
   ClassName = "Linux_OperatingSystem";
   Namespaces = {"root/cimv2"};
   ProviderType = { 2 }; // Instance
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};


// ===================================================================
// 	Linux_UnixProcess
// ===================================================================

instance of PG_ProviderModule
{
   Name = "OSBase_UnixProcessProviderModule";
   Location = "cmpiOSBase_UnixProcess";
   Vendor = "SBLIM";
   Version = "2.0.0";
   InterfaceType = "CMPI";
   InterfaceVersion = "2.0.0";
};

instance of PG_Provider
{
   ProviderModuleName = "OSBase_UnixProcessProviderModule";
   Name = "OSBase_UnixProcess";
};

instance of PG_ProviderCapabilities
{
   ProviderModuleName = "OSBase_UnixProcessProviderModule";
   ProviderName = "OSBase_UnixProcess";
   CapabilityID = "1";
   ClassName = "Linux_UnixProcess";
   Namespaces = {"root/cimv2"};
   ProviderType = { 2 }; // Instance
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};


// ===================================================================
// 	Linux_Processor
// ===================================================================

instance of PG_ProviderModule
{
   Name = "OSBase_ProcessorProviderModule";
   Location = "cmpiOSBase_Processor";
   Vendor = "SBLIM";
   Version = "2.0.0";
   InterfaceType = "CMPI";
   InterfaceVersion = "2.0.0";
};

instance of PG_Provider
{
   ProviderModuleName = "OSBase_ProcessorProviderModule";
   Name = "OSBase_Processor";
};

instance of PG_ProviderCapabilities
{
   ProviderModuleName = "OSBase_ProcessorProviderModule";
   ProviderName = "OSBase_Processor";
   CapabilityID = "1";
   ClassName = "Linux_Processor";
   Namespaces = {"root/cimv2"};
   ProviderType = { 2 }; // Instance
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};



// -------------------------------------------------------------------
// *******************************************************************
// 	Associations
// *******************************************************************
// -------------------------------------------------------------------


// ===================================================================
// 	Linux_RunningOS
// ===================================================================

instance of PG_ProviderModule
{
   Name = "OSBase_RunningOSProviderModule";
   Location = "cmpiOSBase_RunningOS";
   Vendor = "SBLIM";
   Version = "2.0.0";
   InterfaceType = "CMPI";
   InterfaceVersion = "2.0.0";
};

instance of PG_Provider
{
   ProviderModuleName = "OSBase_RunningOSProviderModule";
   Name = "OSBase_RunningOS";
};

instance of PG_ProviderCapabilities
{
   ProviderModuleName = "OSBase_RunningOSProviderModule";
   ProviderName = "OSBase_RunningOS";
   CapabilityID = "1";
   ClassName = "Linux_RunningOS";
   Namespaces = {"root/cimv2"};
   ProviderType = { 2,3 }; // Association
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};


// ===================================================================
// 	Linux_OSProcess
// ===================================================================

instance of PG_ProviderModule
{
   Name = "OSBase_OSProcessProviderModule";
   Location = "cmpiOSBase_OSProcess";
   Vendor = "SBLIM";
   Version = "2.0.0";
   InterfaceType = "CMPI";
   InterfaceVersion = "2.0.0";
};

instance of PG_Provider
{
   ProviderModuleName = "OSBase_OSProcessProviderModule";
   Name = "OSBase_OSProcess";
};

instance of PG_ProviderCapabilities
{
   ProviderModuleName = "OSBase_OSProcessProviderModule";
   ProviderName = "OSBase_OSProcess";
   CapabilityID = "1";
   ClassName = "Linux_OSProcess";
   Namespaces = {"root/cimv2"};
   ProviderType = { 2,3 }; // Association
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};


// ===================================================================
// 	Linux_CSProcessor
// ===================================================================

instance of PG_ProviderModule
{
   Name = "OSBase_CSProcessorProviderModule";
   Location = "cmpiOSBase_CSProcessor";
   Vendor = "SBLIM";
   Version = "2.0.0";
   InterfaceType = "CMPI";
   InterfaceVersion = "2.0.0";
};

instance of PG_Provider
{
   ProviderModuleName = "OSBase_CSProcessorProviderModule";
   Name = "OSBase_CSProcessor";
};

instance of PG_ProviderCapabilities
{
   ProviderModuleName = "OSBase_CSProcessorProviderModule";
   ProviderName = "OSBase_CSProcessor";
   CapabilityID = "1";
   ClassName = "Linux_CSProcessor";
   Namespaces = {"root/cimv2"};
   ProviderType = { 2,3 }; // Association
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};



