//
// Linux_BaseRegistration.mof
//
// (C) Copyright IBM Corp. 2002
//
// THIS FILE IS PROVIDED UNDER THE TERMS OF THE COMMON PUBLIC LICENSE
// ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS FILE
// CONSTITUTES RECIPIENTS ACCEPTANCE OF THE AGREEMENT.
//
// You can obtain a current copy of the Common Public License from
// http://oss.software.ibm.com/developerworks/opensource/license-cpl.html
//
// Author:       Heidi Neumann <heidineu@de.ibm.com>
// Contributors:
//
// Description:
// CIM classes for Linux Base System Instrumentation
//


#pragma locale ("en_US")
#pragma namespace ("root/PG_InterOp")

// ===================================================================
// 	Linux_ComputerSystem
// ===================================================================


instance of PG_ProviderModule
{
   Name = "OSBase_ComputerSystemProviderModule";
   //The library name on disk
   Location = "cmpiOSBase_ComputerSystemProvider";
   Vendor = "SBLIM";
   Version = "2.0.0";
   InterfaceType = "CMPI";
   InterfaceVersion = "2.0.0";
};

instance of PG_Provider
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "OSBase_ComputerSystemProviderModule";
   // The provider name as referenced in the code
   Name = "OSBase_ComputerSystemProvider";
};

instance of PG_ProviderCapabilities
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "OSBase_ComputerSystemProviderModule";
   //The provider name as defined in PG_Provider
   ProviderName = "OSBase_ComputerSystemProvider";
   CapabilityID = "1";
   //Name of the CIM class as defined in the mof
   ClassName = "Linux_ComputerSystem";
   Namespaces = {"root/cimv2"};
   ProviderType = { 2,4 }; // Instance, Method
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};

// ===================================================================
// 	Linux_OperatingSystem
// ===================================================================

instance of PG_ProviderModule
{
   Name = "OSBase_OperatingSystemProviderModule";
   //The library name on disk
   Location = "cmpiOSBase_OperatingSystemProvider";
   Vendor = "SBLIM";
   Version = "2.0.0";
   InterfaceType = "CMPI";
   InterfaceVersion = "2.0.0";
};

instance of PG_Provider
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "OSBase_OperatingSystemProviderModule";
   // The provider name as referenced in the code
   Name = "OSBase_OperatingSystemProvider";
};

instance of PG_ProviderCapabilities
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "OSBase_OperatingSystemProviderModule";
   //The provider name as defined in PG_Provider
   ProviderName = "OSBase_OperatingSystemProvider";
   CapabilityID = "1";
   //Name of the CIM class as defined in the mof
   ClassName = "Linux_OperatingSystem";
   Namespaces = {"root/cimv2"};
   ProviderType = { 2,4 }; // Instance, Method
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};


// ===================================================================
// 	Linux_UnixProcess
// ===================================================================

instance of PG_ProviderModule
{
   Name = "OSBase_UnixProcessProviderModule";
   //The library name on disk
   Location = "cmpiOSBase_UnixProcessProvider";
   Vendor = "SBLIM";
   Version = "2.0.0";
   InterfaceType = "CMPI";
   InterfaceVersion = "2.0.0";
};

instance of PG_Provider
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "OSBase_UnixProcessProviderModule";
   // The provider name as referenced in the code
   Name = "OSBase_UnixProcessProvider";
};

instance of PG_ProviderCapabilities
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "OSBase_UnixProcessProviderModule";
   //The provider name as defined in PG_Provider
   ProviderName = "OSBase_UnixProcessProvider";
   CapabilityID = "1";
   //Name of the CIM class as defined in the mof
   ClassName = "Linux_UnixProcess";
   Namespaces = {"root/cimv2"};
   ProviderType = { 2,4 }; // Instance, Method
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};


// ===================================================================
// 	Linux_Processor
// ===================================================================

instance of PG_ProviderModule
{
   Name = "OSBase_ProcessorProviderModule";
   //The library name on disk
   Location = "cmpiOSBase_ProcessorProvider";
   Vendor = "SBLIM";
   Version = "2.0.0";
   InterfaceType = "CMPI";
   InterfaceVersion = "2.0.0";
};

instance of PG_Provider
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "OSBase_ProcessorProviderModule";
   // The provider name as referenced in the code
   Name = "OSBase_ProcessorProvider";
};

instance of PG_ProviderCapabilities
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "OSBase_ProcessorProviderModule";
   //The provider name as defined in PG_Provider
   ProviderName = "OSBase_ProcessorProvider";
   CapabilityID = "1";
   //Name of the CIM class as defined in the mof
   ClassName = "Linux_Processor";
   Namespaces = {"root/cimv2"};
   ProviderType = { 2,4 }; // Instance, Method
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};



// -------------------------------------------------------------------
// *******************************************************************
// 	Associations
// *******************************************************************
// -------------------------------------------------------------------


// ===================================================================
// 	Linux_RunningOS
// ===================================================================


instance of PG_ProviderModule
{
   Name = "OSBase_RunningOSProviderModule";
   //The library name on disk
   Location = "cmpiOSBase_RunningOSProvider";
   Vendor = "SBLIM";
   Version = "2.0.0";
   InterfaceType = "CMPI";
   InterfaceVersion = "2.0.0";
};

instance of PG_Provider
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "OSBase_RunningOSProviderModule";
   // The provider name as referenced in the code
   Name = "OSBase_RunningOSProvider";
};

instance of PG_ProviderCapabilities
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "OSBase_RunningOSProviderModule";
   //The provider name as defined in PG_Provider
   ProviderName = "OSBase_RunningOSProvider";
   CapabilityID = "1";
   //Name of the CIM class as defined in the mof
   ClassName = "Linux_RunningOS";
   Namespaces = {"root/cimv2"};
   ProviderType = { 2,3 }; // Instance, Association
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};


// ===================================================================
// 	Linux_OSProcess
// ===================================================================

instance of PG_ProviderModule
{
   Name = "OSBase_OSProcessProviderModule";
   //The library name on disk
   Location = "cmpiOSBase_OSProcessProvider";
   Vendor = "SBLIM";
   Version = "2.0.0";
   InterfaceType = "CMPI";
   InterfaceVersion = "2.0.0";
};

instance of PG_Provider
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "OSBase_OSProcessProviderModule";
   // The provider name as referenced in the code
   Name = "OSBase_OSProcessProvider";
};

instance of PG_ProviderCapabilities
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "OSBase_OSProcessProviderModule";
   //The provider name as defined in PG_Provider
   ProviderName = "OSBase_OSProcessProvider";
   CapabilityID = "1";
   //Name of the CIM class as defined in the mof
   ClassName = "Linux_OSProcess";
   Namespaces = {"root/cimv2"};
   ProviderType = { 2,3 }; // Instance, Association
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};


// ===================================================================
// 	Linux_CSProcessor
// ===================================================================


instance of PG_ProviderModule
{
   Name = "OSBase_CSProcessorProviderModule";
   //The library name on disk
   Location = "cmpiOSBase_CSProcessorProvider";
   Vendor = "SBLIM";
   Version = "2.0.0";
   InterfaceType = "CMPI";
   InterfaceVersion = "2.0.0";
};

instance of PG_Provider
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "OSBase_CSProcessorProviderModule";
   // The provider name as referenced in the code
   Name = "OSBase_CSProcessorProvider";
};

instance of PG_ProviderCapabilities
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "OSBase_CSProcessorProviderModule";
   //The provider name as defined in PG_Provider
   ProviderName = "OSBase_CSProcessorProvider";
   CapabilityID = "1";
   //Name of the CIM class as defined in the mof
   ClassName = "Linux_CSProcessor";
   Namespaces = {"root/cimv2"};
   ProviderType = { 2,3 }; // Instance, Association
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};
