//
// Linux_Base.mof
//
// Copyright (c) 2002, International Business Machines
//
// THIS FILE IS PROVIDED UNDER THE TERMS OF THE COMMON PUBLIC LICENSE
// ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS FILE
// CONSTITUTES RECIPIENTS ACCEPTANCE OF THE AGREEMENT.
//
// You can obtain a current copy of the Common Public License from
// http://oss.software.ibm.com/developerworks/opensource/license-cpl.html
//
// Author:       Heidi Neumann <heidineu@de.ibm.com>
// Contributors:
//
// Description:
// CIM classes for Linux Base System Instrumentation
//


#pragma locale ("en_US")


// -------------------------------------------------------------------
// *******************************************************************
// 	Classes
// *******************************************************************
// -------------------------------------------------------------------



// ===================================================================
// 	Linux_ComputerSystem
// ===================================================================

[ Provider("cmpi:cmpiOSBase_ComputerSystemProvider"),
  Description ("A class derived from ComputerSystem"
  " to represent the GNU/Linux OS on a Desktop, Mobile, NetPC,"
  " Server or other type of a single node Computer System ." )
]
class Linux_ComputerSystem : CIM_ComputerSystem
{ };


// ===================================================================
// 	Linux_OperatingSystem
// ===================================================================

[ Provider("cmpi:cmpiOSBase_OperatingSystemProvider") ]
class Linux_OperatingSystem : CIM_OperatingSystem
{
  [ Description("Average total cpu time in percents."),
    Units("Percent")
  ]
  uint16 PctTotalCPUTime;

  uint8 execCmd([IN] string cmd, [OUT] string out);
};


// ===================================================================
// 	Linux_UnixProcess
// ===================================================================

[ Provider("cmpi:cmpiOSBase_UnixProcessProvider") ] 
class Linux_UnixProcess : CIM_UnixProcess
{
  uint32 MaxNumberOfChildProcesses ;
  uint32 MaxNumberOfOpenFiles ;
  uint32 MaxRealStack ;

  uint8 terminate();
};


// ===================================================================
// 	Linux_Processor
// ===================================================================

[ Provider("cmpi:cmpiOSBase_ProcessorProvider") ] 
class Linux_Processor : CIM_Processor
{ };



// -------------------------------------------------------------------
// *******************************************************************
// 	Associations
// *******************************************************************
// -------------------------------------------------------------------


// ===================================================================
// 	Linux_RunningOS
// ===================================================================

[ Association, 
  Provider("cmpi:cmpiOSBase_RunningOSProvider") ] 
class Linux_RunningOS : CIM_RunningOS
{
  [ Override ("Antecedent"),
    Description ("The current running OS.")
  ]
  Linux_OperatingSystem REF Antecedent;

  [ Override ("Dependent"),
    Description ("The Computer System Container.")
  ]
  Linux_ComputerSystem REF Dependent; 
};


// ===================================================================
// 	Linux_OSProcess
// ===================================================================

[ Association, 
  Aggregation,
  Composition, 
  Provider("cmpi:cmpiOSBase_OSProcessProvider") ] 
class Linux_OSProcess : CIM_OSProcess
{
  [ Override ("GroupComponent"),
    Description ("The current running OS.")
  ]
  Linux_OperatingSystem REF GroupComponent;

  [ Override ("PartComponent"),
    Description ("The current running Processes.")
  ]
  Linux_UnixProcess REF PartComponent;
};


// ===================================================================
// 	Linux_CSProcessor
// ===================================================================

[ Association, 
  Aggregation,
  Composition,
  Provider("cmpi:cmpiOSBase_CSProcessorProvider") ] 
class Linux_CSProcessor : CIM_SystemDevice
{ 
  [ Override ("GroupComponent"),
    Description ("The Computer System Container.")
  ]
  Linux_ComputerSystem REF GroupComponent;

  [ Override ("PartComponent"),
    Description ("The Processors, available to the CS.")
  ]
  Linux_Processor REF PartComponent;
};

