# Makefile for SBLIM Base Instrumentation 


# SNIA CIMOM flavor
include ../setting.cmpi

install: 
	install -m 644 Linux_Base.mof $(CIMOMMOF)/Linux_Base.mof

uninstall:
	$(RM) $(CIMOMMOF)/Linux_Base.mof








